apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-angular-service
spec:
  selector:
    app: {{ .Release.Name }}-angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
